### ISSUE TITLE
Using ipRange with localhost:3000

### ISSUE THREAD

**Issue by abumere** [jasonsims/aws-cloudfront-sign#34]
Is it possible to make signed URL's for localhost:3000? This is what Im currently trying below but can't get it to work, 

 var options = {
    keypairId: config.cloudFrontAccessKeyId,
    privateKeyPath: config.cloudFrontSecretKeyPath,
    expireTime: new Date().getTime() + 1800000,
    ipRange: '127.0.0.0/8'
  };

Also, Im assuming the ipRange should be entered as a string. It wasn't clear in the api doc

**Comment by jasonsims** [comment]
No, I don't believe it's possible to do this. The `ipRange` key is used by cloudfront to allow specific public IPs access to the signed content.

**Comment by abumere** [comment]
@jasonsims ok got it. Also if I wanted to get the ip of the client (ip of user who is accessing the page) how would I do that server side? is it normally passed when the request (GET etc) is made serverside?

**Comment by jasonsims** [comment]
You could try using https://github.com/pbojinov/request-ip

**Comment by abumere** [comment]
First, thanks for the quick feedback so far... 

So I'm still having a hard time getting this ipRange to work with any ip Address range.. even without the port number. **The singed urls work when an Ip is not specified but I get an 'access denied' when I specify an ip.**

I am testing locally so I am using 127.0.0.1 ip and im passing **ipRange: '127.0.0.1/32'**
as the param. 

Looking into the source I noticed you're creating a canned policy and not a custom one. I couldn't find anywhere on aws's doc's that says canned policies accept ipRange as a parameter. They are explicit that custom ones do. Could that be why I cant get this to work? Or could it be that I'm using the localhost ip 127.0.0.1 as a ipRange field??? 

Been trying to get this to work for a couple days and Im not sure if this is something with code to how the url's are generated with ip's.

Any help is appreciated!!!

**Comment by jasonsims** [comment]
The only difference between canned and custom policies is that custom policies must be included in the signed url under the `Policy` param because they are nondeterministic. I admit the class naming in CannedPolicy.js is misleading and should be updated. However, you can see on [cloudfrontUtil.js#L34](https://github.com/jasonsims/aws-cloudfront-sign/blob/a8d5579f7cbaa5e0ae737dd063300f9128aa8d6a/lib/cloudfrontUtil.js#L34) that the policy is always included within the signed URL so both canned and custom policies will work.

I still believe this issue you are hitting is that you are using your private localhost address of 127.0.0.1 and not your public IP. AWS evaluates the public address of the incoming request against  the value given when you signed the URL. Try substituting 127.0.0.1 for whatever value is shown when you visit http://www.whatsmyip.org/

**Comment by abumere** [comment]
I see, I didn't take that into account. 

I just ran a test using my public IP with signing a url and it worked. Thanks for the help!

This issue unique to the fact that Im running AND accessing it locally right? In deployment, when a user accesses my page I could grab their IP using the library you mentioned above and it would be their public facing IP thats returned right? 

Once again Thanks

**Comment by jasonsims** [comment]
Yeah, that should work.
