### ISSUE TITLE
generateCookies Failing Silently when dockerized

### ISSUE THREAD

**Issue by gristoi** [jasonsims/aws-cloudfront-sign#36]
Hi, I have been trying to debug this issue for a few days now.

If i am running this package locally on my machine using reacts-web-app webpack setup it works fine. the second i move it into a dockerized environment the package dies silently.

the code i'm currently testing with is this:

`let options = {
        keypairId: "ABCDEFGHIJKL",
        privateKeyPath:"./cloudfront.pem",
        expireTime: new Date().getTime() + 6000000
    };
    console.log("HERE")
    let cookies = cfsign.getSignedCookies('http://cdn-dev.my-sitet.com/*', options);
    console.log(cookies)`

so I only get 'HERE' outputting in the console, nothing after
have you come across any issue with this and docker?

**Comment by gristoi** [comment]
ok, ive done a bit more digging and found that the signing is catchable, so now i cans see what error i am getting.

am getting this error

Error: sorry, createSign is not implemented yet
we accept pull requests
http://github.com/dominictarr/crypto-browserify
    at error (http://localhost:3000/static/js/bundle.js:72903:10)
    at Object.exports.(anonymous function) [as createSign] (http://localhost:3000/static/js/bundle.js:72945:6)
    at _createPolicySignature (http://localhost:3000/static/js/bundle.js:70801:22)
    at Object.getSignedCookies (http://localhost:3000/static/js/bundle.js:70729:20)
    at saveToCookie (http://localhost:3000/static/js/bundle.js:69402:48)

**Comment by jasonsims** [comment]
It seems that the [crypto-browserify](https://github.com/crypto-browserify/crypto-browserify) package is being used and it does not support the `createSign` method used during url/cookie signing. You can see the error your getting here
https://github.com/crypto-browserify/crypto-browserify/blob/master/index.js#L71

I suspect the issue is related to something in the webpack process since I am not using crypto-browserify in this package but am using the built-in crypto library within node. 
https://nodejs.org/api/crypto.html#crypto_crypto_createsign_algorithm

**Comment by jasonsims** [comment]
I don't recommend using this library in the front-end since it could expose your AWS keys to the public.
